Edicao e qtde palavras
jplukas/desafio-dafiti pull request #3
Opened 2021-03-11 19:33 UTC by jplukas

# Alterações (pedidas na Issue #2):
* Criação do campo last_update, persistindo a data da última atualização
* Modificação do tipo do campo created_at para DateTimeField, para mais precisão
* Ordenação dos posts por data de atualização
* Criação de rotas e páginas para criação e edição de posts
* Visualização de quantidade de palavras no conteúdo de cada post
   * Foi preciso instalar um plugin (wordcount - https://ckeditor.com/cke4/addon/wordcount) para visualização da quantidade de palavras **_durante_** a edição

2021-03-12 13:53 UTC, rockyshimithy commented on myblog/forms.py
> +from . import models
O que acha de usar imports absolutos?
Na maioria dos casos aqui no Automation usamos esse tipo de import justamente para deixar explicito.
```suggestion
from models import Post
```

2021-03-12 13:54 UTC, rockyshimithy commented on myblog/forms.py
> +        model = models.Post
Dado a mudança a acima, aqui ficaria: 
```suggestion
        model = Post
```
O que acha?

2021-03-12 13:55 UTC, rockyshimithy commented on myblog/migrations/0004_auto_20210311_1909.py
> +class Migration(migrations.Migration):
Considerando o escopo de uma tarefa só (branch/PR), o que acha de deixar toda mudança do model em um migration só?

2021-03-12 13:56 UTC, rockyshimithy commented on myblog/models.py
> +    last_updated = models.DateTimeField(auto_now=True)
Aqui talvez seja frescura da minha parte com nome de campo/variavel, mas o que acha de
```suggestion
    updated_at = models.DateTimeField(auto_now=True)
```
pra ficar consistente com o campo de cima?

2021-03-12 13:59 UTC, rockyshimithy commented on myblog/templates/index.html
> +        {% with wc=post.content|striptags|wordcount %}
🚀

2021-03-12 14:00 UTC, rockyshimithy commented on myblog/views.py
> +from . import models, forms
mesmo ponto sobre import relativo para absoluto.

2021-03-12 14:00 UTC, rockyshimithy commented on myblog/views.py
> +        posts = models.Post.objects.order_by('-last_updated')
🚀

2021-03-12 14:01 UTC, rockyshimithy commented on myblog/views.py
>  class index(View):
É mais comum e encorajamos usar nome das classses em camel case, entao ficaria
```suggestion
class Index(View):
```
enquanto as funcoes continnuam em snake case.

2021-03-12 14:02 UTC, rockyshimithy commented on myblog/views.py
>  class index(View):
o mesmo para o detail

2021-03-12 14:03 UTC, rockyshimithy commented on myblog/views.py
>  class index(View):
e NewPost

2021-03-12 14:03 UTC, rockyshimithy commented on myblog/views.py
> +    return render(request, 'index.html', {'posts' : posts, 'user_page' : user})
por que tu optou em mudar o nome dessa var?

2021-03-12 14:05 UTC, rockyshimithy commented on myblog/views.py
> +        return render(request, 'edit_post.html', {'form' : form, 'action' : 'new'})
por que html de edit_post?

2021-03-12 14:10 UTC, rockyshimithy requested changes
Tem bastante arquivo css, fonts, license e js, será que não conseguimos dar uma bela enxugada para ter apenas o que realmente é utilizado e necessário?

2021-03-12 21:10 UTC, jplukas commented on myblog/models.py
> +    last_updated = models.DateTimeField(auto_now=True)
Boa!

2021-03-12 21:12 UTC, jplukas commented on myblog/views.py
> +        return render(request, 'edit_post.html', {'form' : form, 'action' : 'new'})
Na verdade esse template é usado tanto para editar quanto para criar um novo post, mas esse nome está meio confuso...
Vou fazer uma alteração

2021-03-12 21:14 UTC, jplukas commented on myblog/migrations/0004_auto_20210311_1909.py
> +class Migration(migrations.Migration):
Boa, vou tentar fazer um squashmigrations

2021-03-12 21:18 UTC, jplukas commented on myblog/views.py
> +    return render(request, 'index.html', {'posts' : posts, 'user_page' : user})
Porque acho que esse nome user, quando eu referenciava no template, estava causando um bug...
Sempre que eu tentava acessar /myblog/posts sem estar logado no admin, aparecia um erro. Com essa alteração esse erro parou de acontecer

2021-03-15 11:37 UTC, tiagoprn commented on myblog/views.py
> +        return render(request, 'edit_post.html', {'form' : form, 'action' : 'new'})
Pode ser uma boa renomear o template nesse caso então para create_update_post.html, ou algo assim, por questão de legibilidade... :wink:

2021-03-15 11:40 UTC, tiagoprn commented on myblog/templates/index.html
> +        <p class="blog-post-meta">{{ post.updated_at }} by <a href="{% url 'user_posts' post.author.id %}">{{ post.author.get_full_name }}</a> ({{wc}} word{{wc|pluralize}})
Boa sacada em usar o pluralize! :rocket:

2021-03-15 11:42 UTC, tiagoprn reviewed
Bom trabalho @jplukas , deixei algumas sugestões também.

2021-03-16 18:28 UTC, tiagoprn approved these changes
Sucesso @jplukas ! :1st_place_medal:

2021-03-16 18:42 UTC, merged

2021-03-16 20:53 UTC, rockyshimithy commented on myblog/migrations/0004_auto_20210311_1909.py
> +class Migration(migrations.Migration):
eita nao sabia que dava pra dar squash de migrations, bacana.

2021-03-16 20:53 UTC, rockyshimithy commented on myblog/migrations/0004_auto_20210311_1909.py
> +class Migration(migrations.Migration):
meu ponto era só deletar os arquivos e criar novamente uma só